### ISSUE TITLE
Benchmark uses non optimized wasm builds

### ISSUE THREAD

**Issue by MaxGraey** [IulianOctavianPreda/AssemblyScript-WebAssemblyVsJS-SeqventialVsParallelProcessing#1]
Hi. Just want to note that according to this:
https://github.com/IulianOctavianPreda/AssemblyScript-WebAssemblyVsJS-SeqventialVsParallelProcessing/blob/master/package.json#L9

your benchmark uses unoptimized wasm versions. For turn on opts plz add `-O3` flag for all `asc` commands

**Comment by MaxGraey** [comment]
Also here:
https://github.com/IulianOctavianPreda/AssemblyScript-WebAssemblyVsJS-SeqventialVsParallelProcessing/blob/master/assembly/quicksort.ts#L2

instead: `array[Math.floor((right + left) / 2) as i32];`
you could use simply `array[(right + left) / 2];` or `array[(right + left) >>> 1];`

**Comment by IulianOctavianPreda** [comment]
Thank you for your review!

I'll definitely change it to `array[(right + left) / 2]`.

As for the non-optimized build, isn't the flag already set in the [asconfig.json](https://github.com/IulianOctavianPreda/AssemblyScript-WebAssemblyVsJS-SeqventialVsParallelProcessing/blob/master/asconfig.json). I used a different target with optimizations for every AssemblyScript file.

And as a general question for you, since you are a core developer for AssemblyScript, is it in your opinion the comparison I am trying to make fair? I'll explain below, mind you everything is still at the beginning.

In general terms, I am trying to compare the performance of the produces WASM to the produces JS. I want to measure 2 things, the overall time spent for the X feature/algorithm that I am running(that is with loading async the JS/WASM file and running the benchmark), and the time spent running only the benchmark.
 
For the parallel version, these 2 timings are not that different as the async load of the JS/WASM file is done in the worker rather than in the benchmark function and there is no way to pass around the loaded functions.
 
As mentions, I want to do this in both Node and Chrome and the entire bundle is UMD so it can be used regardless of the runtime.
Also, I used the Typescript compiler extended with the AssemblyScript types to generate the JS files used for comparison. I did that for  2 reasons 
- I had some problems with the generated JS files from AssemblyScript, especially the abort function and afterwards the actual usage of the generated code (I don't think I found documentation for it if it was available please point me to it) as it seems to be using still some but not the same methods as the WASM version.
- The TS code was closer to the expected JS. For that, I had to globally patch functions like `idof`. The actual patching does not influence the measurements and calling a function that returns void or the argument passed should be quite ok I think.

**Comment by MaxGraey** [comment]
I see. You're use targets. In this ase I still recommend change  from:
```
"optimizeLevel": 3,
"shrinkLevel": 1,
```
which equivalent to "-O3s" to
```
"optimizeLevel": 3,
"shrinkLevel": 0,
```
which equivalent to `-O3`

**Comment by MaxGraey** [comment]
btw this:
```ts
min = Math.ceil(min) as i32;
max = Math.floor(max) as i32;
```
also unnecessary

**Comment by MaxGraey** [comment]
Also wondering what if you add `unchecked` for array's access in quick-sort

**Comment by IulianOctavianPreda** [comment]
Thank you for your help.
I incorporated your changes. The generated WASM is much faster now. 
I'll compile a new batch of data after some other improvements are completed.
